### ISSUE TITLE
problem when i use

### ISSUE THREAD

**Issue by Cathgao** [MikuAuahDark/Itsudemo#1]
it always says 'permission denied'

**Comment by MikuAuahDark** [comment]
Try to run it as root. You might not have permission to write in the
current directory.
26 Agt 2016 00.37, "Cathgao" notifications@github.com menulis:

**Comment by Cathgao** [comment]
but i am using the Windows7 and XP, and the i have the full permission of the directory
![Uploading 1.png…]()

**Comment by MikuAuahDark** [comment]
Are you sure you have full access to the directory where the TEXB files lies?

**Comment by Cathgao** [comment]
of course

**Comment by MikuAuahDark** [comment]
Try to run it as Administrator and see if it works.

**Comment by Cathgao** [comment]
![1](https://cloud.githubusercontent.com/assets/21031564/18026352/97aab1dc-6c76-11e6-8547-4399e7bce70a.png)
I run as Administrator, but you see, it doesn't work.

**Comment by MikuAuahDark** [comment]
Itsudemo doesn't support opening a directory. Specify the TEXB file path, not the directory.

Also, try to move the files to directory which doesn't contain any unicode characters. Itsudemo doesn't supports unicode.
