### ISSUE TITLE
u_31009001_normal_navi gives wrong result here

### ISSUE THREAD

**Issue by iebb** [MikuAuahDark/Itsudemo#2]
![u_31009001_rankup_navi](https://cloud.githubusercontent.com/assets/2127498/18759723/5f6fe494-8130-11e6-86a8-3d878f561ecd.png)

**Comment by MikuAuahDark** [comment]
That's known problem and currently there is no workaround except extracting
the whole texture bank.
23 Sep 2016 01.52, "Jebwiz Oscar" notifications@github.com menulis:

**Comment by MikuAuahDark** [comment]
Just to note, v1.0.6 already have that issue fixed. https://github.com/MikuAuahDark/Itsudemo/commit/9ad393a254d76767a48ed25935bca64353b80598
